export const dealsGradeExpectationsData = [
  {
    grade: "associate",
    expectation: {
      operationalExcellence:
        "Manage your time and availability proactively to support team deadlines and maintain work/life balance. Engage actively with your team and seniors, sharing progress updates and collaborating on assigned tasks. Demonstrate ownership of your work, showing understanding of your responsibilities and reflecting on areas for growth. Book chargeable and non-chargeable hours accurately and timeously. Consider efficient use of time and when addressing review comments.",
      deliveryExcellence: {
        preEngagement:
          "Demonstrate an understanding of risk management procedures and independence requirements, and confidentiality protocols. Execute accurately, timeously and according to firm policy, with coaching and guidance from your team. Support Save-it file setup and initial documentation with guidance. Demonstrate initiative and support with business development and proposals. Research and read through industry/market data relevant to the engagement. Leverage the resources and materials available to you and engage with your seniors to fully understand what is required of you. Demonstrate a basic understanding of all the TS competencies (i.e., FDD, SPA, ADA, V&BM, WC CF and VC (including DDV, DS, OiD, PiD, TiD)) and other Deals competencies (Valuations & BM, Corporate Finance, CARS).",
        engagementAdmin:
          "Create and maintain a Travel & Expense (T&E) summary for each project, and document inputs collated from the rest of your team. Prepare meeting agendas using PwC templates and circulate them to relevant stakeholders ahead of scheduled client engagements, with guidance from your team. Document meeting minutes accurately and upload all relevant project documentation to SaveIt files/Engagement Hub promptly.",
        engagementDelivery:
          "Demonstrates problem-solving skills, and analytical thinking that is appropriate for your level. Seek opportunities to learn more about the overall deal on which you are working, rather than only focusing on your assigned section(s). Proactively seek coaching and feedback on-the-job and identify development areas upfront. Adhere to the deadlines set for assigned tasks. Seek guidance on how long a task should take and flag items that may take longer in advance. Ensure timely follow-up on all post-meeting action items, escalating any delays or issues to the senior team members. Utilise the Smart functionality when preparing deliverables. Build in accuracy checks in Dealtools/Datapacks to source data. Assist with drafting various pieces of the deliverable(s) (e.g., report/Deal tool/other) and demonstrate basic report-writing skills (able to work on different types of reports, and contribute to assigned sections using a template and/or with extensive guidance from the Engagement Manager). Self-review your assigned work before sending it for review including basic consistency and formatting checks. Assist with a reconciliation of the scope of work, with guidance from your team. Take ownership of your career development: request feedback within two weeks after completion of a project, supported by a face-to-face discussion.",
        digitalDelivery:
          "You should be familiar and upskilled in Engagement Hub and the platforms it supports. This involves being able to work competently in each of the key digital tools (i.e., Alteryx, Data Studio, Power BI, Junction) so that you can provide input and support as required. Leveraging PwC approved AI tools – you should be familiar with (by completing the recommended training) and make use of the full functionality of ChatPwC (across all available LLMs), CoPilot and Ask Junction. Ensure all client and target meetings are transcribed for potential AI-enabled analysis. Rules of engagement for using Generative AI – only use PwC approved GenAI tools for learning and engagements. Never input PwC or client confidential/personal data into public GenAI. Treat all AI output as first drafts which should be subjected to full self-review and review by senior team members before selection for content of deliverables. Review all AI output in storyboarding sessions with senior team members to test accuracy, commerciality, and business acumen. Develop prompts together with senior oversight to ensure commercial appropriateness of prompting. Escalate any uncertainties about data use or tool scope to your senior. Capture prompts/sources and perform simple verification (e.g., check citations, run sense checks).",
        postEngagement:
          "Assist with file completion and Save-it wrap-up tasks. Request feedback within two weeks of project completion.",
      },
    },
  },
  {
    grade: "senior associate",
    expectation: {
      operationalExcellence:
        "Deliver on multiple commitments of a straightforward/simple nature throughout the project. Utilise PwC’s full range of capabilities (i.e., DealsIQ, Salesforce, TS Resource shared drive, A&C, etc.) and manage these requests and workflows. Seek exposure to a range of different types of work within your area of specialism (i.e., request to be responsible for certain sections/analyses up front).",
      deliveryExcellence: {
        preEngagement:
          "Assist with Save-it filing and appropriate documentation (from the outset of the project through to completion) and other risk management procedures and independence requirements, including initial drafting of Engagement Letters, with guidance from the Engagement Manager. Obtain a broad understanding of the key markets in which our clients operate. Understand major business and industry trends/issues from available data, and use this to prepare for meetings. Proactively agree your role on the project upfront.",
        engagementAdmin:
          "Contribute to creating, updating, and reconciling the information request list (including a VDR where relevant), and question lists. Contribute to the preparation of a question pack (related to your area of work) for management/expert meetings. Review the VDR on a frequent basis and read through relevant materials. Track actual costs for yourself and the team against the engagement budget and communicate this on a timely basis to the Engagement Manager.",
        engagementDelivery:
          "Perform critical self-review checks on your own analyses and slides to minimise errors. This step is critical for safeguarding quality, enhancing credibility, and minimising errors that could impact client trust and engagement timelines. Examples of self-review checks include spell-check, check calculations, reconcile control totals, validate source references, and ensure formatting and writing style aligns with PwC presentation standards. Use TS best practices (Smart reporting, Deal Guide, etc.) to prepare standard analyses that are clear, concise, and accurate. Be prepared to talk through envisaged complexities with senior team members when undertaking complex analyses. Take responsibility in following up on client questions and internal/external requests. Flag any findings or questions from the sections to which you were assigned to other members of the team. Ensure that the Engagement Manager is updated on the status of your work, including bottlenecks, on a timely basis. Proactively reach out to senior team members for coaching on sections of work which you are assigned. Be curious and show initiative by seeking input from others within the engagement team to sense check analyses, seek ‘smarter’ working practices, and use this for all workings and deliverables. Take ownership of your allocated work (e.g., Deal tool/analyses and slides). Take ownership of analyses and follow up on any review comments; consider these key learning areas going forward. Demonstrate developing report writing skills (including appropriate use of TS presentation standards, and an ability to execute your own sections and provide reasonable commentary and interpretation of issues, with guidance from the Engagement Manager). Draft input into emails to be shared with the client, its advisors, and other workstreams regarding initial observations, questions, and process matters.",
        digitalDelivery:
          "You should be familiar and upskilled in Engagement Hub and the platforms it supports. This involves being able to work competently in each of the key digital tools (i.e., Alteryx, Data Studio, Power BI, Junction) so that you can provide input and support as required. Delivering insights – add and edit content in a Junction report, as well as write sections within the report. Leveraging PwC approved AI tools – you should be familiar with (by completing the recommended training) and make use of the full functionality of ChatPwC (across all available LLMs), CoPilot, and Ask Junction. Ensure all client and target meetings are transcribed for potential AI-enabled analysis. Rules of engagement for using Generative AI – only use PwC approved GenAI tools for learning and engagements. Never input PwC or client confidential/personal data into public GenAI. Treat all AI output as first drafts which should be subjected to full self-review and review by senior team members before inclusion in deliverables. Review all AI output in storyboarding sessions with senior team members to test accuracy, commerciality, and business acumen. Develop prompts together with senior oversight to ensure commercial appropriateness of prompting. Escalate any uncertainties about data use or tool scope to your senior. Capture prompts/sources and perform simple verification (e.g., check citations, run sense checks). Data preparation – build workflows to cleanse and flatfile data. Data modelling – prepare and deploy a data model using Data Studio and connect this to your analysis tool(s) of choice. Data visualisation – build basic analysis using files connected to the Data Studio cube.",
        postEngagement:
          "Take ownership of Save-it file completion and risk management wrap-up tasks. Participate in post-deal feedback discussions and document learnings.",
        fddSpecific:
          "Develop a strong understanding of the target’s business model and how it translates into the financial statements. This includes identifying key revenue drivers, cost structures, and operational metrics, and linking these to financial performance indicators. Understand the purpose and objectives of flagship analyses such as Quality of Earnings (QoE), Net Working Capital (NWC), and debt-like items (DDL), and how they impact deal value. Calculate and present relevant/useful KPIs. Build foundational skills, including data interpretation, variance analysis, and scenario modelling. Assist with certain pieces of analyses using Data & Analytics tools, with guidance.",
        vcSpecific:
          "Show a basic proficiency in T&E management, including Work-In-Progress (WIP) reconciliations and provision calculations, and invoicing with support from the Engagement Manager. Assist other team members with business development efforts, including the preparation of proposals and related documentation.",
      },
    },
  },
  {
    grade: "manager level 1",
    expectation: {
      operationalExcellence:
        "Recognise the value of different perspectives (other team members, clients, advisors) and challenge and establish a point of view whenever appropriate to contribute to the overall success of the project. Start to build and maintain a broad network that extends beyond TS (i.e., x-LoS, peers at clients, etc.). Demonstrate curiosity and initiative by contributing to project team-working and proactively seeking ways in which to assist the completion of the project beyond your assigned work/sections. Proactively engage with and facilitate the exchange of ideas with multi-territory teams. Keep abreast of how local and global economic factors affect the client and the transaction.",
      deliveryExcellence: {
        preEngagement:
          "Contribute to drafting of scopes of work and engagement letters, under the direction of the senior team members. Understand and execute risk management procedures and independence requirements using the required capabilities (i.e., Salesforce, A&C, TS Resource shared drive, etc.), with guidance from senior team members. Proactively contribute to initial internal meetings through research and available material.",
        engagementAdmin:
          "Align expectations with the Senior Manager on matters such as project management, development areas, etc., upfront. Assume a proactive role in project management without senior follow-up/monitoring: communicate project status and provide timely and accurate updates. Track actual costs for self against the engagement budget and communicate this on a timely basis to the project leader. Book chargeable hours timeously and accurately. Track efficient use of time and consider admin and internal investment when addressing review comments. Schedule timely Engagement Manager review, leaving appropriate time for further review comments if necessary. Immediately upon the opening of the VDR, proactively assist in updating the IRL for your sections. Review the VDR documents for your assigned section and check the VDR for relevant updates on a frequent basis. Ensure timely and accurate completion of project wrap-up tasks.",
        engagementDelivery:
          "Critically self-review analyses and slides to minimise errors and review notes and include Excel checks (to ensure appropriate use of banner headlines, correct spelling and grammar, views expressed balanced with clear messaging, no inconsistencies, etc.). Develop report writing skills. Deal tools should be prepared and constantly maintained as though they are independent deliverables that can be submitted to the client at any point during the engagement process without significant additional work/effort, including ‘clean’ and consistent analyses/tabs; appropriate formatting and wording; control totals; reconciliations with appropriate and consistent source documentation, etc. Use TS best practices (i.e., Smart, Deal Guide) to prepare non-standard/specific analyses that are accurate and concise. Prepare sections of the question pack relevant to your sections and take ownership of those (i.e., ensuring all responses have been obtained from management). When undertaking complex analysis, consult with senior team members and discuss potential solutions. Check for, and address, review notes timeously (as you may not always be tagged in review comments from your senior team members/Partner). Estimate the time required to build new analyses/update for new information and discuss this with the team. Take ownership of certain sections of the report, ensuring that you are agreeing to and meeting internal review deadlines and proactively communicating any potential delays well in advance.",
        digitalDelivery:
          "You should take responsibility for the full data lifecycle on your projects. This means you should be comfortable using the digital tools yourself, and therefore able to coach your team members. You should also encourage the adoption of the digital tools across your projects. Delivering insights – add and edit content in a Junction report, as well as write sections within the report and review work performed by junior team members. Leveraging PwC approved AI tools – you should be familiar with (by completing the recommended training) and make use of the full functionality of ChatPwC (across all available LLMs), CoPilot, and Ask Junction. Participate in storyboarding sessions to determine which AI outputs are relevant for client reporting. Ensure all client and target meetings are transcribed for potential AI-enabled analysis. Rules of engagement for using Generative AI – only use PwC approved GenAI tools for learning and productivity. Never input PwC or client confidential/personal data into public GenAI. Treat all AI output as first drafts which should be reviewed and validated for accuracy, relevance, and alignment with client expectations before inclusion in deliverables. Review your own and more junior team members’ output. Review all AI output in storyboarding sessions with senior team members to test accuracy, commerciality, and business acumen. Develop prompts together with senior oversight to ensure commercial appropriateness of prompting. Act as the first point of escalation for data use concerns and tool limitations. Promote documentation of prompts and sources. Ensure verification steps are consistently applied across engagements. Data preparation – build workflows to cleanse and flatfile data, as well as review and edit workflows created by an Associate or the AC. Data modelling – prepare and deploy a data model using Data Studio, or review a model built by an Associate or the AC. Data visualisation – build basic analysis using files connected to the Data Studio cube, including more complex analyses.",
        postEngagement:
          "Ensure full risk management wrap-up and file completion. Participate in post-deal feedback sessions and identify future opportunities.",
        fddSpecific:
          "Deepen understanding of how the target’s business model translates into financial performance and informs key diligence analyses. Understand and communicate major business trends/issues from data provided and communicate these. Ensure that analyses prepared address the relevant outcome (e.g., preparing ageing analysis by currency/country for a geographically diverse target). Understand the key FDD analyses (QofE, Net Debt, and NWC) and how assigned sections can have an impact on this. Discuss questions/findings with seniors. Calculate and present relevant KPIs that are tracked by management (rather than presenting a KPI dump). To the extent the AC Kolkata is used, ensure that you take full ownership of the output including reconciliations of the AC Kolkata output to the source information. Use of the AC Kolkata should only be after approval by the senior on the job after you present/justify the benefits of using AC Kolkata.",
        vcSpecific:
          "Contribute to all business development efforts, including drafting and refining proposals. Demonstrate an ability to support projects across all VC-competencies (DDV, DS, OiD, PiD, TiD), as required. Able to independently manage basic workstreams including leading workstream meetings. With guidance from the Engagement Manager, track and review project economics (e.g., WIP reconciliations, provision calculations, recovery calculations, etc.). Follow up as appropriate with the client/target/advisors on outstanding requests and questions.",
      },
    },
  },
  {
    grade: "manager level 2",
    expectation: {
      operationalExcellence:
        "Begin to respond directly to clients, advisors, and/or potential buyers on certain aspects related to the project, and use prior deal knowledge and experience as a reference point. Demonstrate an ability to make decisions and exercise judgement, with confirmation from the Engagement Manager. Reflect on and communicate where your own work may have been performed more efficiently to improve subsequent engagement recoveries (e.g., through the use of Data & Analytics tools). Appreciate the different working styles and customs of individuals and teams on an engagement (e.g., aligning different working hours). Show an understanding of the perspectives of all stakeholders involved in a deal (e.g., seller vs buyer objectives, corporate strategic buyer vs private equity expectations). Lead and proactively encourage the exchange of ideas with multi-territory teams. Proactively engage with peers within other Deal Advisory departments, i.e., M&A, CARS, Valuation and Business Modelling, Tax, and Legal, during an assignment with multiple workstreams. Look for opportunities to strengthen and expand your internal network in order to leverage these relationships when the current project requires specific expertise.",
      deliveryExcellence: {
        preEngagement:
          "Proactively initiate and coach junior team members on risk management procedures and independence requirements, and documentation of the Save-it file planning tasks. Formulate a view on the engagement approach and raise it proactively with the Engagement Manager/Partner. Agree with the Engagement Manager on the format of internal and client meetings, and who should provide status updates, request client feedback, share results with the team, and act upon this.",
        engagementAdmin:
          "Assume overall ownership of project admin, review from a holistic perspective, and delegate tasks as appropriate (e.g., preparing and updating the IRL, question packs, VDR management, etc.). In addition to keeping the Engagement Manager updated with the project status and bottlenecks, keep a list of possible reasons for overruns, with detailed support to quantify the value of the estimated overrun, and communicate it timeously to your Engagement Manager and Partner. Have a clear overview of the information on the VDR/data received in relation to your own analyses and analyses assigned to more junior members of the team.",
        engagementDelivery:
          "Take ownership of assigned deliverable sections by the communicated project deadline and be able to deliver on multiple commitments, even under pressure. Take ownership of assigned report sections, committing to ensuring completeness of slides from a review note and information update perspective, even when planned on another engagement. Take ownership of your assigned sections in the question pack during the management meeting and follow up thereafter. Identify areas of value-add and insights to the client based on your analyses and communicate this with the team. Be able to facilitate meetings, demonstrating confidence and aptitude. Show professional scepticism when obtaining management responses (i.e., probe on responses that do not make sense). Proactively discuss and share best practices with the wider team and coach inexperienced team members on industry and deal-specific topics related to the project. Consider insightful questions/topics/complex sections of work for discussion internally and externally. Manage the Deal tool/report-writing process, including communicating formatting/conventions upfront. Liaise with your network of peers and seniors from other lines of service across Deals, Consulting, and Strategy to get useful insights relevant to your project. Provide insight on key items to communicate to the client.",
        digitalDelivery:
          "You should take responsibility for the full data lifecycle on your projects. This means you should be comfortable using the digital tools yourself, and therefore able to coach your team members. You should also encourage the adoption of the digital tools across your projects. Delivering insights – add and edit content in a Junction report, as well as write sections within the report and review work performed by junior team members. Leveraging PwC approved AI tools – you should be familiar with (by completing the recommended training) and make use of the full functionality of ChatPwC (across all available LLMs), CoPilot, and Ask Junction. Participate in storyboarding sessions to determine which AI outputs are relevant for client reporting. Ensure all client and target meetings are transcribed for potential AI-enabled analysis. Rules of engagement for using Generative AI – only use PwC approved GenAI tools for learning and productivity. Never input PwC or client confidential/personal data into public GenAI. Treat all AI output as first drafts which should be reviewed and validated for accuracy, relevance, and alignment with client expectations before inclusion in deliverables. Review your own and more junior team members’ output. Review all AI output in storyboarding sessions with senior team members to test accuracy, commerciality, and business acumen. Develop prompts together with senior oversight to ensure commercial appropriateness of prompting. Act as the first point of escalation for data use concerns and tool limitations. Promote documentation of prompts and sources. Ensure verification steps are consistently applied across engagements. Data preparation – build workflows to cleanse and flatfile data, as well as review and edit workflows created by an Associate or the AC. Data modelling – prepare and deploy a data model using Data Studio, or review a model built by an Associate or the AC. Data visualisation – build basic analysis using files connected to the Data Studio cube, including more complex analyses.",
        postEngagement:
          "Ensure full risk management wrap-up and file completion. Participate in post-deal feedback sessions and identify future opportunities.",
        fddSpecific:
          "Manage the Deal tool process, including communicating formatting/conventions upfront. Consider and present analyses that address specific key risk topics relevant to each engagement, rather than just populating standard FDD analyses. Identify QofE, Net Debt, and NWC items (one-offs, run rate, pro-forma) and write factually accurate slides highlighting key messages. Identify and calculate KPIs that are tracked by management and/or are relevant to understanding business trends (e.g., fuel prices for a target in the logistics industry).",
        vcSpecific:
          "Take further ownership in management of project economics and keep the Engagement Manager/Partner updated. Be able to independently manage simple and straightforward projects, facilitate client meetings, and coordinate multiple stakeholders and workstreams, with support from the Engagement Partner.",
      },
    },
  },
  {
    grade: "manager level 3",
    expectation: {
      operationalExcellence:
        "Assist with business development initiatives, such as supporting on proposal writing, and identifying opportunities at existing clients or through internal and external networks; challenge the Engagement Partner on pro-actively involving you in various aspects of the deal (from proposal to execution) to build your experience and networks; use wider firm and personal relationships to respond to opportunities and client requests; engage and involve other LoS and competences within Deals to increase multi-team efficiencies and ensure client issues/objectives are addressed; modify behaviour to align with different working styles and customs of multi-disciplinary or multi-territory teams (e.g., accommodating different working hours/reporting structure/review hierarchy); lead discussions on local/global economic factors impacting clients/target within the team and with the client.",
      deliveryExcellence: {
        preEngagement:
          "Proactively and independently identify and resolve (through the relevant network) complex risk-management related considerations/procedures from commencement to completion of an engagement, ensuring follow-through and appropriate documentation; lead and contribute to discussion on key internal and client planning meetings, especially on smaller projects (in terms of fee and team size), from an industry and deal specific perspective.",
        engagementAdmin:
          "Manage and delegate project management, such as communicating project status (internally and externally), WIP/overruns/invoicing, scheduling and coordinating timely partner/concurring reviews, and leading management and internal meetings (on smaller projects); identify development areas for the team early on through coaching and reviewing; identify ahead of time anticipated budget variances and track and communicate reasons for variances to the Director/Senior Manager to improve recovery from an overall perspective; highlight scope creep to the Engagement Partner and ensure the risk management is appropriately addressed and included in the overrun tracker; coach junior team members in the preparation of the IRL and ensure that it covers the scope.",
        engagementDelivery:
          "Lead/run smaller projects (in terms of fees and team members); show capability of running/owning client meetings; identify relevant information to send to clients, advisors, and other workstreams and take the lead in communication (draft emails, etc.); take responsibility for the question pack and agenda for management/expert meetings and manage priority of the questions and responses during meetings; prepare insightful questions/topics that address key risk areas and show agility in management discussion (i.e., be prepared to discuss new topics/information); manage the follow-up after a management meeting and ensure that communication to all stakeholders is clear; keep the team, client, and advisors directly informed of follow-up points and issues identified throughout the transaction process; assess the overall quality of information received and the impact on envisaged deliverables, making recommendations to the Engagement Partner when it is appropriate to “put pens down”/“pick up”; proactively prepare and contribute to overall storyboarding sessions, beyond sections on which you are assigned, in line with client priority areas and the scope of work; take responsibility for and be able to address more complex analyses/issues by making well-considered suggestions to approach/analyses; execute deliverables with limited re-work; provide on-the-job coaching of incremental complexity to junior team members; perform first review of analyses and sections prepared by juniors to ensure consistent messaging and factual accuracy (ensuring the right balance between reminding the reader of the issue and being concise); connect with peer contacts at the client and maintain contact also after the deal.",
        digitalDelivery:
          "You should take responsibility for the full data lifecycle on your projects. This means you should be comfortable using the digital tools yourself, and therefore able to coach your team members. You should also encourage the adoption of the digital tools across your projects. Delivering insights – add and edit content in a Junction report, as well as write sections within the report and review work performed by junior team members. Leveraging PwC approved AI tools – you should be familiar with (by completing the recommended training) and make use of the full functionality of ChatPwC (across all available LLMs), CoPilot, and Ask Junction. Participate in storyboarding sessions to determine which AI outputs are relevant for client reporting. Ensure all client and target meetings are transcribed for potential AI-enabled analysis. Rules of engagement for using Generative AI – only use PwC approved GenAI tools for learning and productivity. Never input PwC or client confidential/personal data into public GenAI. Treat all AI output as first drafts which should be reviewed and validated for accuracy, relevance, and alignment with client expectations before inclusion in deliverables. Review your own and more junior team members’ output. Review all AI output in storyboarding sessions with senior team members to test accuracy, commerciality, and business acumen. Develop prompts together with senior oversight to ensure commercial appropriateness of prompting. Act as the first point of escalation for data use concerns and tool limitations. Promote documentation of prompts and sources. Ensure verification steps are consistently applied across engagements. Data preparation – build workflows to cleanse and flatfile data, as well as review and edit workflows created by an Associate or the AC. Data modelling – prepare and deploy a data model using Data Studio, or review a model built by an Associate or the AC. Data visualisation – build basic analysis using files connected to the Data Studio cube, including more complex analyses.",
        postEngagement:
          "Ensure full risk management wrap-up and file completion; lead post-deal feedback sessions and identify future opportunities.",
        fddSpecific:
          "Determine QofE, Net Debt, and NWC adjustments in a thoughtful way, having an opinion on the approach and providing pros and cons of approaches where relevant; the same applies for other FDD analyses. Identify opportunities to leverage the Acceleration Centre, but critically consider and substantiate to the Director/Senior Manager the benefits of this versus assigning the task internally.",
        vcSpecific:
          "Drive business development initiatives allocated to you based on your role; lead client update and higher-complexity workstream meetings; participate when called upon in SteerCo sessions to provide detail of a specific workstream topic.",
      },
    },
  },
  {
    grade: "manager level 4",
    expectation: {
      operationalExcellence:
        "Leverage the PwC Network to obtain market knowledge and value add considerations for the client and reporting purposes; work effectively with cross-LoS/global/diverse teams to ensure consistency and quality of deliverables; navigate complex discussions, consult internally, and cater your communication style to specific audiences; handle requests based on level of urgency and reach consensus to balance expectations of various stakeholders (team, client, advisors); create a team environment that encourages continuous learning, well-being, and inclusion; seek out different perspectives when approaching challenges and developing solutions; take the lead in client communication and ensure that client expectations are managed; assist with business development initiatives, such as supporting on proposal writing and identifying opportunities at existing clients or through internal and external networks.",
      deliveryExcellence: {
        preEngagement:
          "Proactively and independently oversee the finalisation of risk management from start to end, including direct follow-up with R&Q/SDC/etc.; actively contribute to addressing the team’s personal development areas through allocation of relevant tasks and responsibilities; identify opportunities for efficiencies in budgeting, such as through the use of Data & Analytics tools.",
        engagementAdmin:
          "Lead management and internal meetings; lead and delegate all elements of project administration; lead internal discussions with the Partner/Director/Senior Manager relating to engagement recoveries and be prepared to support variances.",
        engagementDelivery:
          "Lead and take responsibility for storyboarding sessions, including appropriate focus on transaction nuances and key focus areas; appreciate the impact of differing client expectations on the deliverable (e.g., storyboard a report structure which addresses specific risks for a client rather than rolling forward a standard TS report template); identify the need for TS/firm subject matter expert input; critically review information prepared by the team before submission to the target/client; perform a first review of certain sections of the report prior to it going for second; ensure that key points are dealt with adequately and that issues are clearly articulated; manage and delegate quality review of client deliverables through ensuring internal checks and consistency of messaging/formatting; comfortably lead less-complex projects with minimal guidance.",
        digitalDelivery:
          "You should take responsibility for the full data lifecycle on your projects. This means you should be comfortable using the digital tools yourself, and therefore able to coach your team members. You should also encourage the adoption of the digital tools across your projects. Delivering insights – add and edit content in a Junction report, as well as write sections within the report and review work performed by junior team members. Leveraging PwC approved AI tools – you should be familiar with (by completing the recommended training) and make use of the full functionality of ChatPwC (across all available LLMs), CoPilot, and Ask Junction. Participate in storyboarding sessions to determine which AI outputs are relevant for client reporting. Ensure all client and target meetings are transcribed for potential AI-enabled analysis. Rules of engagement for using Generative AI – only use PwC approved GenAI tools for learning and productivity. Never input PwC or client confidential/personal data into public GenAI. Treat all AI output as first drafts which should be reviewed and validated for accuracy, relevance, and alignment with client expectations before inclusion in deliverables. Review your own and more junior team members’ output. Review all AI output in storyboarding sessions with senior team members to test accuracy, commerciality, and business acumen. Develop prompts together with senior oversight to ensure commercial appropriateness of prompting. Act as the first point of escalation for data use concerns and tool limitations. Promote documentation of prompts and sources. Ensure verification steps are consistently applied across engagements. Data preparation – build workflows to cleanse and flatfile data, as well as review and edit workflows created by an Associate or the AC. Data modelling – prepare and deploy a data model using Data Studio, or review a model built by an Associate or the AC. Data visualisation – build basic analysis using files connected to the Data Studio cube, including more complex analyses.",
        postEngagement:
          "Ensure full risk management wrap-up and file completion; lead post-deal feedback sessions and identify future opportunities.",
        fddSpecific:
          "Take ownership of reviewing other workstream deliverables to identify any issues impacting QofE, Net Debt, NWC and key views to align with the ‘Business Diligence’ approach to reporting.",
        vcSpecific:
          "Drive business development initiatives allocated to you based on your role. Participate in SteerCo sessions as appropriate based on the project size and complexity.",
      },
    },
  },
  {
    grade: "senior manager",
    expectation: {
      operationalExcellence:
        "Lead and manage complex, multi-territory, cross-LoS engagements and take overall leadership/management of all workstreams on the project, delegating as appropriate; build a specialism within an industry, keeping up with technical and market developments and sharing fresh insights with clients and other teams; utilise your professional network within the firm to obtain subject matter expert input/opinions when required or relevant; use internal networks (local and global) to provide global and market-specific views and findings for the client; proactively seek to engage and check in with clients even when not on an active project; facilitate opportunities for team members to grow their own network during an assignment (e.g., delegating responsibility, with guidance, for a team/workstream to a more experienced manager); identify and pursue business opportunities through personal networks, industry news, and client interactions; convert leads into clients by aligning PwC services with identified needs, contributing to the growth and sustainability of the practice; negotiate with clients to secure engagements, manage expectations, and build long-term relationships; drive business development initiatives, such as supporting on proposal writing and identifying opportunities at existing clients or through internal and external networks; support the growth of the TS team through non-client initiatives (i.e., training, recruitment, business development, wellness initiatives, coaching, etc.); support recruitment and retention initiatives; support people capability development through knowledge sharing and participation in internal trainings.",
      deliveryExcellence: {
        preEngagement:
          "Ensure risk management is finalised and perform review on a timely basis in accordance with ECR/EQR standards; review scope of work and engagement letters, ensuring clarity, compliance, and alignment with client needs; identify opportunities for other LoS and competencies within Deals SA, Africa, and/or globally while on assignment (either revenue-generating or sharing a client relationship).",
        engagementAdmin:
          "Accurately update Retain with the resources you will use on projects in a timely manner; oversee client invoicing and debtor collections, ensuring accuracy and timeliness; actively contribute to and manage the team to ensure acceptable recoveries on projects; review and communicate Work-In-Progress (WIP) reconciliations and provision calculations in a timely manner, and arrange billing and invoicing; lead external discussions with the client relating to overruns and engagement recoveries, and be prepared to support variances; review and approve Save it file tasks in a timely manner; maintain relationships with the client post-deal and request feedback, identifying potential opportunities as a result of this feedback; proactively monitor feedback exchange requests and discuss/complete with the Director or Partner.",
        engagementDelivery:
          "Take full ownership of project deliverables, ensuring execution aligns with defined scope, timelines, and quality benchmarks; ensure tasks are appropriately assigned and delegated, providing upfront and ongoing coaching to team members to promote upskilling and efficiencies on projects; manage client engagements by supporting junior team members in their interactions and taking control of the project/engagement; provide high-level coaching and guidance to junior and mid-level team members, fostering a culture of excellence, accountability, and continuous development; review work performed by team members, ensuring alignment with project scope, quality standards, and client expectations; demonstrate an understanding of the client’s key deal focus areas through non-standard, out-of-the-box, or specific analyses and commentary to appropriately address such areas; actively follow up with the client on key deal issues; identify complex issues in a timely manner, develop knowledge to capture relevant deal risks, and leverage PwC expertise to address them. Focus on technical areas of an engagement that may have a significant impact on deal value and/or client considerations; engage in difficult conversations with clients regarding project delays, overruns, or scope changes, maintaining professionalism and trust; maintain relationships with the client post-deal and request feedback, identifying potential opportunities as a result of this feedback; lead by example in adopting and promoting digital tools, advising the team on their use, benefits, and integration across the data lifecycle; lead client and workstream meetings with the client and participate in SteerCo meetings, if applicable.",
        digitalDelivery:
          "Advise your team on how to approach the data lifecycle, understanding and articulating how digital tools work, their benefits, and use cases, while being comfortable reviewing analysis connected to a data model; deliver insights by adding and editing content in a Junction report, writing sections, and reviewing work done by others; leverage PwC-approved AI tools, becoming familiar with and using the full functionality of ChatPwC (across all available LLMs), CoPilot, and Ask Junction; provide oversight on AI use by guiding prompting techniques, reviewing outputs for accuracy, and leading brainstorming/storyboarding sessions; champion responsible and strategic use of Generative AI tools across engagements, ensuring alignment with PwC policies and client confidentiality standards, and ensuring team members only use PwC-approved GenAI tools; lead storyboarding sessions to critically assess AI-generated content, guiding teams on commercial and strategic refinement; drive best practices in prompt engineering and GenAI usage across teams, mentoring junior team members; establish frameworks for prompt documentation, source validation, and output verification to ensure consistency and auditability; collaborate with leadership to evolve GenAI guidelines and training based on emerging use cases and risks. Data preparation by reviewing and editing workflows created by the AC or more junior team members, providing coaching as needed; data modelling by reviewing a data model built in Data Studio and making updates if required; data visualisation by building analyses using files connected to the Data Studio cube, while coaching more junior team members.",
        postEngagement:
          "Lead risk management wrap-up and ensure the Save-it file is complete and ECR-ready; maintain client relationships post-deal and leverage feedback for business development.",
        fddSpecific:
          "Contribute to discussions, with the support of the Partner/Director, with the client around key principles from an SPA and deal-value perspective, such as the net working capital mechanism, EV to Equity bridge, locked box versus completion accounts considerations; demonstrate advanced understanding of the Engagement Hub, Junction, Power BI, and other digital tools, articulating their use cases and benefits; review analysis connected to data models, ensuring insights are accurate, actionable, and aligned with project goals.",
        vcSpecific:
          "Review strawman and final client deliverables, providing strategic input and ensuring consistency and impact in a timely manner; take ownership of the Steering Committee packs and lead Steering Committee meetings, if applicable to the project.",
      },
    },
  },
];
