// export const gradeExpectationsData = [
//   {
//     grade: "associate",
//     expectation:
//       "Apply a learning mindset and take ownership for your own development. Appreciate diverse perspectives, needs, and feelings of others. Adopt habits to sustain high performance and develop your potential. Actively listen, ask questions to check understanding, and clearly express ideas. Seek, reflect, act on, and give feedback. Gather information from a range of sources to analyse facts and discern patterns. Commit to understanding how the business works and build commercial awareness. Learn and apply professional and technical standards (e.g., refer to specific PwC tax and audit guidance), uphold the firm’s code of conduct and independence requirements. Demonstrate quality and technical expertise in line with your role. Understand the drivers of utilisation and how your contributions impact team capacity and client delivery. Proactively drive your own client projects and business development utilisation. Proactively seek opportunities to support client engagements. Communicate availability and interests clearly to managers and engagement leads.",
//   },
//   {
//     grade: "senior associate",
//     expectation:
//       "Respond effectively to the diverse perspectives, needs, and feelings of others. Use a broad range of tools, methodologies, and techniques to generate new ideas and solve problems. Use critical thinking to break down complex concepts. Apply previous knowledge and experiences to be successful in new situations. Understand the broader objectives of your project or role and how your work fits into the overall strategy. Develop a deeper understanding of the business context and how it is changing. Guide others to help build their skills and knowledge. Understand and effectively interpret feedback for yourself and others. Use reflection to develop self-awareness, enhance strengths, and address development areas. Interpret data to inform insights and recommendations. Uphold and reinforce professional and technical standards (e.g., refer to specific PwC tax and audit guidance), the firm’s code of conduct, and independence requirements. Demonstrate quality and technical expertise in line with your role. Proactively communicate your availability and interests to managers and engagement leads. Identify and pursue opportunities to contribute across engagements.",
//   },
//   {
//     grade: "manager",
//     expectation:
//       "Expand and share your network across a diverse range of people and teams. Ask questions to deepen understanding for yourself and others. Analyse and identify the linkages and interactions between the component parts of an entire system. Take ownership of projects, ensuring their successful planning, budgeting, execution, and completion. Partner with team leadership to ensure collective ownership of quality, timelines, and deliverables. Develop skills outside your comfort zone, and encourage others to do the same. Effectively mentor others. Use the review of work as an opportunity to deepen the expertise of team members. Address conflicts or issues, engaging in difficult conversations with clients, team members, and other stakeholders, escalating where appropriate. Identify and escalate issues which may put the firm’s reputation at risk. Uphold and reinforce professional and technical standards (e.g., refer to specific PwC tax and audit guidance), the firm’s code of conduct, and independence requirements. Demonstrate quality and technical expertise in line with your role. Anticipate resourcing needs and collaborate with senior managers to align availability.",
//   },
//   {
//     grade: "senior manager",
//     expectation:
//       "Craft and convey clear, impactful, and engaging messages that tell a holistic story. Create an environment where rapid experimentation can thrive. Apply systems thinking to identify underlying problems and/or opportunities. Validate outcomes with clients, share alternative perspectives, and act on client feedback. Influence others to gain alignment and move things forward. Direct the team through complexity, demonstrating composure through ambiguous, challenging, and uncertain situations. Deepen and evolve your expertise with a focus on staying relevant. Maximise the potential of others and facilitate opportunities for growth. Initiate open and honest coaching conversations at all levels. Identify opportunities to grow the business. Make difficult decisions and take action to resolve issues hindering team effectiveness. Model and reinforce professional and technical standards (e.g., refer to specific PwC tax and audit guidance), the firm’s code of conduct, and independence requirements. Demonstrate quality and technical expertise in line with your role. Champion a culture of proactive utilisation management. Lead by example in managing your own utilisation and guiding others to do the same. Partner with leadership to forecast needs and align talent to opportunities.",
//   },
//   {
//     grade: "director",
//     expectation:
//       "Lead in line with our values and brand. Develop new ideas, solutions, and structures; drive thought leadership. Embrace new ways to deliver client value through alternative delivery models. Solve problems by exploring multiple angles and using creativity, encouraging others to do the same. Balance long-term, short-term, detail-oriented, and big-picture thinking. Make strategic choices and drive change by addressing system-level enablers. Set the tone and drive accountability for a healthy, resilient, equitable, and inclusive team culture. Role model continuous learning, empathy, and feedback. Recognise your accountability for the firm’s brand and financial success. Promote technological advances, creating an environment where people and technology thrive together. Identify gaps in the market and convert opportunities to success for the firm. Adhere to and enforce professional and technical standards (e.g., refer to specific PwC tax and audit guidance), the firm’s code of conduct, and independence requirements. Demonstrate quality and technical expertise in line with your role.",
//   },
//   {
//     grade: "partner",
//     expectation:
//       "Lead in line with our values and brand. Generate and share a strategic vision that others can aspire to and commit to. Exemplify the desired skills, behaviours, and values to influence the performance of others. Realise distinctive client outcomes by bringing multidisciplinary capabilities/relevance, including outside your own expertise and revenue stream. Anticipate the impact of future technology; upskill self and others to maintain relevance. Actively seek new ways to deliver client value through alternative delivery models. Capitalise on opportunities caused by change and disruption to generate new business. Pioneer thought leadership that enhances the firm’s position in the marketplace. Champion agility and adaptability as the market changes. Embrace continuous personal growth and development, fostering a collaborative environment of shared experiences and learning. Sponsor and grow a diverse pipeline of future talent for the benefit of the wider firm. Exemplify courage with integrity, take bold action, and own a culture of mutual accountability in the partnership. Mitigate evolving risks, role modelling appropriate risk taking. Adhere to and enforce professional and technical standards (e.g., refer to specific PwC tax and audit guidance), the firm’s code of conduct, and independence requirements. Demonstrate and drive accountability across the team for quality and technical expertise.",
//   },
// ];
