import { Request, Response } from "express";
import { NextFunction } from "express";
import { StatusCodes } from "http-status-codes";
import { hashPassword, comparePassword } from "../utils/password.js";
import { generateToken } from "../utils/jwt.js";
import {
  findUserByEmail,
  createUser,
  findByUserId,
  updateUserGrade,
} from "../db/queries.js";

export const signup = async (
  req: Request,
  res: Response<
    | {
        user: { id: number; email: string; grade?: string | null };
        message: string;
      }
    | { message: string }
  >,
  next: NextFunction
) => {
  try {
    const { email, password, grade } = req.body;

    if (!email || !password) {
      return res
        .status(StatusCodes.BAD_REQUEST)
        .json({ message: "Email and password are required" });
    }

    // Validate grade if provided
    if (grade) {
      const validGrades = [
        "Associate",
        "Senior Associate",
        "Manager Level 1",
        "Manager Level 2",
        "Manager Level 3",
        "Manager Level 4",
        "Senior Manager",
      ];
      if (!validGrades.includes(grade)) {
        return res
          .status(StatusCodes.BAD_REQUEST)
          .json({ message: "Invalid grade" });
      }
    }

    const existingUser = await findUserByEmail(email);

    if (existingUser.length > 0) {
      return res
        .status(StatusCodes.CONFLICT)
        .json({ message: "User already exists" });
    }

    const hashedPassword = await hashPassword(password);

    const [newUser] = await createUser(email, hashedPassword, grade);

    const token = generateToken(
      { userId: newUser.insertId, email }, // payload - extract id from newUser.insertId (generated by DB) and email from req.body
      process.env.JWT_SECRET || ""
    );

    res.cookie("token", token, {
      httpOnly: true, // prevent JS access to cookie (block XSS)
      secure: process.env.NODE_ENV === "production", // HTTPS
      sameSite: "lax", // Use "lax" for subdomains (same root domain) - works better on mobile
      maxAge: 7 * 24 * 60 * 60 * 1000, // 7 days
      domain:
        process.env.NODE_ENV === "production"
          ? ".notlocalhost.ink" // Root domain with leading dot for subdomain sharing
          : undefined,
    });

    const responseUser = {
      id: newUser.insertId,
      email,
      grade: grade || null,
    };

    res.status(StatusCodes.CREATED).json({
      user: responseUser,
      message: "User created successfully",
    });
  } catch (error) {
    next(error);
  }
};

export const login = async (
  req: Request,
  res: Response<
    | { user: { id: number; email: string }; message: string }
    | { message: string }
  >,
  next: NextFunction
) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res
        .status(StatusCodes.BAD_REQUEST)
        .json({ message: "Email and password are required" });
    }

    const existingUser = await findUserByEmail(email);

    if (existingUser.length === 0) {
      return res
        .status(StatusCodes.NOT_FOUND)
        .json({ message: "User not found" });
    }

    const isPasswordCorrect = await comparePassword(
      password,
      existingUser[0].passwordHash
    );

    if (!isPasswordCorrect) {
      return res
        .status(StatusCodes.UNAUTHORIZED)
        .json({ message: "Invalid password" });
    }

    const token = generateToken(
      { userId: existingUser[0].id, email },
      process.env.JWT_SECRET || ""
    );

    res.cookie("token", token, {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "lax", // Use "lax" for subdomains (same root domain) - works better on mobile
      maxAge: 7 * 24 * 60 * 60 * 1000, // 7 days
      domain:
        process.env.NODE_ENV === "production"
          ? ".notlocalhost.ink" // Root domain with leading dot for subdomain sharing
          : undefined,
    });

    res.status(StatusCodes.OK).json({
      user: {
        id: existingUser[0].id,
        email,
      },
      message: "Login successful",
    });
  } catch (error) {
    next(error);
  }
};

export const logout = async (
  req: Request,
  res: Response<{ message: string }>,
  next: NextFunction
) => {
  try {
    res.clearCookie("token", {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "lax",
      path: "/", // must match login
      domain:
        process.env.NODE_ENV === "production"
          ? ".notlocalhost.ink" // Must match domain used in login/signup
          : undefined,
    });
    res.status(StatusCodes.OK).json({ message: "Logout successful" });
  } catch (error) {
    next(error);
  }
};

export const getMe = async (
  req: Request,
  res: Response<
    | { user: { id: number; email: string; grade?: string | null } }
    | { message: string }
  >,
  next: NextFunction
) => {
  try {
    const [user] = await findByUserId(req.user.userId);

    if (!user) {
      return res
        .status(StatusCodes.NOT_FOUND)
        .json({ message: "User not found" });
    }
    res.status(StatusCodes.OK).json({
      user: {
        id: user.id,
        email: user.email,
        grade: user.grade,
      },
    });
  } catch (error) {
    next(error);
  }
};

export const updateGrade = async (
  req: Request<{}, {}, { grade: string }>,
  res: Response<{ message: string; grade: string } | { message: string }>,
  next: NextFunction
) => {
  try {
    const { userId } = req.user;
    const { grade } = req.body;

    if (!grade) {
      return res
        .status(StatusCodes.BAD_REQUEST)
        .json({ message: "Grade is required" });
    }

    // Validate grade is one of the allowed values
    const validGrades = [
      "Associate",
      "Senior Associate",
      "Manager Level 1",
      "Manager Level 2",
      "Manager Level 3",
      "Manager Level 4",
      "Senior Manager",
    ];

    if (!validGrades.includes(grade)) {
      return res
        .status(StatusCodes.BAD_REQUEST)
        .json({ message: "Invalid grade" });
    }

    await updateUserGrade(userId, grade);

    res.status(StatusCodes.OK).json({
      message: "Grade updated successfully",
      grade,
    });
  } catch (error) {
    next(error);
  }
};
