import { Request, Response } from "express";
import { NextFunction } from "express";
import { StatusCodes } from "http-status-codes";
import { hashPassword, comparePassword } from "../utils/password.js";
import { generateToken } from "../utils/jwt.js";
import { findUserByEmail, createUser, findByUserId } from "../db/queries.js";

export const signup = async (
  req: Request,
  res: Response<
    | { user: { id: number; email: string }; message: string }
    | { message: string }
  >,
  next: NextFunction
) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res
        .status(StatusCodes.BAD_REQUEST)
        .json({ message: "Email and password are required" });
    }

    // check if user already exists
    const existingUser = await findUserByEmail(email);

    if (existingUser.length > 0) {
      return res
        .status(StatusCodes.CONFLICT)
        .json({ message: "User already exists" });
    }

    // hash password
    const hashedPassword = await hashPassword(password);

    // update with hased password and create user
    const [newUser] = await createUser(email, hashedPassword);

    // generate token
    const token = generateToken(
      { userId: newUser.insertId, email }, // payload - extract id from newUser.insertId (generated by DB) and email from req.body
      process.env.JWT_SECRET || ""
    );

    // set cookie
    res.cookie("token", token, {
      httpOnly: true, // Prevents JavaScript access to cookie (blocks XSS attacks)
      secure: process.env.NODE_ENV === "production", // Cookie sent over HTTPS
      sameSite: process.env.NODE_ENV === "production" ? "none" : "lax", // Blocks cross-site requests except navigation links (prevents CSRF attacks)
      maxAge: 7 * 24 * 60 * 60 * 1000, // 7 days
      domain: undefined,
      // process.env.NODE_ENV === "production"
      //   ? ".notlocalhost.ink"
      //   : "localhost",
    });

    // return user
    res.status(StatusCodes.CREATED).json({
      user: {
        id: newUser.insertId,
        email,
      },
      message: "User created successfully",
    });
  } catch (error) {
    next(error);
  }
};

export const login = async (
  req: Request,
  res: Response<
    | { user: { id: number; email: string }; message: string }
    | { message: string }
  >,
  next: NextFunction
) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res
        .status(StatusCodes.BAD_REQUEST)
        .json({ message: "Email and password are required" });
    }

    // check if user exists
    const existingUser = await findUserByEmail(email);

    if (existingUser.length === 0) {
      return res
        .status(StatusCodes.NOT_FOUND)
        .json({ message: "User not found" });
    }

    // check if password is correct
    const isPasswordCorrect = await comparePassword(
      password,
      existingUser[0].passwordHash
    );

    if (!isPasswordCorrect) {
      return res
        .status(StatusCodes.UNAUTHORIZED)
        .json({ message: "Invalid password" });
    }

    // generate token
    const token = generateToken(
      { userId: existingUser[0].id, email },
      process.env.JWT_SECRET || ""
    );

    // set cookie
    res.cookie("token", token, {
      httpOnly: true, // Prevents JavaScript access to cookie (blocks XSS attacks)
      secure: process.env.NODE_ENV === "production", // Cookie sent over HTTPS
      sameSite: process.env.NODE_ENV === "production" ? "none" : "lax", // Blocks cross-site requests except navigation links (prevents CSRF attacks)
      maxAge: 7 * 24 * 60 * 60 * 1000, // 7 days
      domain: undefined,
      // process.env.NODE_ENV === "production"
      //   ? ".notlocalhost.ink"
      //   : "localhost",
    });

    // return user
    res.status(StatusCodes.OK).json({
      user: {
        id: existingUser[0].id,
        email,
      },
      message: "Login successful",
    });
  } catch (error) {
    next(error);
  }
};

export const logout = async (
  req: Request,
  res: Response<{ message: string }>,
  next: NextFunction
) => {
  try {
    res.clearCookie("token");
    res.status(StatusCodes.OK).json({ message: "Logout successful" });
  } catch (error) {
    next(error);
  }
};

export const getMe = async (
  req: Request,
  res: Response<{ user: { id: number; email: string } } | { message: string }>,
  next: NextFunction
) => {
  try {
    const [user] = await findByUserId(req.user.userId);

    if (!user) {
      return res
        .status(StatusCodes.NOT_FOUND)
        .json({ message: "User not found" });
    }
    res.status(StatusCodes.OK).json({
      user: {
        id: user.id,
        email: user.email,
      },
    });
  } catch (error) {
    next(error);
  }
};
